Add some missing key codes to FlxKey
HaxeFlixel/flixel pull request #2638
Opened 2022-09-18 02:07 UTC by Starmapo

I found out that some key codes from my keyboard weren't defined in FlxKey, so I added them. This adds the following keys:
* SCROLL_LOCK
* NUMLOCK
* START (aka Windows key)
* MENU
* BREAK (aka Pause key)
* NUMPADSLASH

Tested on HTML5, HashLink, and Windows; might need more testing on Mac and Linux

2022-09-18 11:15 UTC, Raltyro approved these changes

2022-09-19 19:45 UTC, Geokureli requested changes
1. Verify that `FlxG.keys.pressed.SCROLL_LOCK` will return true on keyboards that have a scroll lock key. If not, we should remove this to avoid confusion.

2. rename START to WINDOWS

2022-09-19 19:45 UTC, Geokureli commented on flixel/input/keyboard/FlxKey.hx
> +	var SCROLL_LOCK = 145;
I tried pressing scroll lock on my On-Screen Keyboard, and `FlxG.keys.pressed.SCROLL_LOCK` never returned true. have you tried this on your machine?

2022-09-19 19:45 UTC, Geokureli commented on flixel/input/keyboard/FlxKey.hx
> +	var START = 15;
This should just be called WINDOWS, I can't find any other places referring to this as the  "start" key

2022-11-21 00:18 UTC, Geokureli commented on flixel/input/keyboard/FlxKeyList.hx
> +		return check(FlxKey.START);
```suggestion
	public var WINDOWS(get, never):Bool;

	inline function get_WINDOWS()
		return check(FlxKey.WINDOWS);
```

2022-11-21 00:18 UTC, Geokureli commented on flixel/input/keyboard/FlxKey.hx
> +	var START = 15;
```suggestion
	var WINDOWS = 15;
```

2022-11-21 00:20 UTC, Geokureli approved these changes

2022-11-21 00:57 UTC, merged