Implement RGB/RGBA detection to `FlxColor.fromString`
HaxeFlixel/flixel pull request #2741
Opened 2023-02-24 14:06 UTC by gamerbross

Convert strings like `rgb(184, 76, 217)` to a FlxColor using fromString. (case-insensitive & ignores white spaces)

Examples:
- `rgb(184, 76, 12)`
- ` rgb  ( 123, 21,0 )`
- `rgb ( 32 , 56 , 63 , 127 )` 
- `rgba(32,56,63,0)` 

```haxe
~/^rgb\s*\((\s*\d{1,3}\s*,?){3,4}\)/i
```

2023-02-24 15:34 UTC, Geokureli commented
why use this instead of `FlxColor.fromRGB(184, 76, 12)`?

2023-02-24 18:42 UTC, gamerbross commented
> why use this instead of `FlxColor.fromRGB(184, 76, 12)`?

To automate things.
For example, when we want a color from a JSON file, and we use the `fromString` function.

2023-02-24 21:08 UTC, Geokureli commented
What tool is creating color strings like this? it seems like a very weird format when tools typically convert 4 ints to a hex int trivially via  `(a << 24 | r << 16 | g << 8 | b)`

I feel like color strings formats specific to your game should be converted in your game's code rather than being automatically done in flixel. otherwise we're adding bloat to a common flixel util for an uncommon use case

2023-02-24 21:14 UTC, Geokureli commented
apparently even github recognizes this format and automatically puts color dots in code, so perhaps its more common than I thought
![image](https://user-images.githubusercontent.com/2609513/221293988-3859d23c-be75-4857-9f8f-2777302f863a.png)

Although, I think this should have it's own method rather than using toString(), lets call it `fromRGBString()`, and add `toRGBString()` as well

2023-02-24 21:17 UTC, Geokureli requested changes
create new `fromRGBString` and `toRGBString` methods

2023-02-24 21:37 UTC, Geokureli commented
also worth noting that `rgba(32,56,63,0)` doesn't work, despite being listed as one of your examples
https://try.haxe.org/#8FBec88e

2023-02-24 23:42 UTC, gamerbross commented
> create new `fromRGBString` and `toRGBString` methods (or suggest alternative names)
> 
> also you should add unit tests here: https://github.com/HaxeFlixel/flixel/blob/dev/tests/unit/src/flixel/util/FlxColorTest.hx to test various inputs/outputs

Is the function `fromRGBString` really necessary?
The point of the `fromString` function is to be able to parse a color in any format.

I'm also working on more changes and being able to parse CMYK, HSB/HSV and HSL color strings and convert a FlxColor to a string with those formats

2023-02-25 18:39 UTC, Geokureli commented
> Is the function `fromRGBString` really necessary?

Yes

> I'm also working on more changes and being able to parse CMYK, HSB/HSV and HSL

This is exactly why we should have specific "fromRGBString" converters, every new method added add more overhead for every call even though 99.9% of people know exactly what conversion method they need

Furthermore, I still don't know of any game tools that spit out string values like this, do you know of any?

2023-03-01 19:27 UTC, closed without merging