Fixed bug causing focus to be lost when pressing TAB.
HaxeFlixel/flixel pull request #2812
Opened 2023-05-23 00:48 UTC by EliteMasterEric

The associated bug can be reproduced in this way:

- Build any project with FLX_DEBUG enabled.
- While in-game, press `TAB`.

Expected behavior is that nothing should happen in-game (unless something is bound to TAB).

Actual behavior is that the window loses focus and the cursor becomes detached from the window.

The root cause is that the console textbox is being focused by OpenFL even when the debugger is not open.

Tested and with this fix the textbox still focuses when the debugger is OPEN (as expected).

2023-05-23 03:24 UTC, MemeHovy commented
I feel like I remember something like that happening before, and that can honestly be a bit of a pet peeve to people, so this is a good change ngl (I don't understand why it wasn't added sooner)

2023-05-23 17:20 UTC, Geokureli commented
nice I'll try this out today

2023-05-23 21:01 UTC, Geokureli requested changes

2023-05-23 21:01 UTC, Geokureli commented on flixel/system/debug/console/Console.hx
> +			if (FlxG.debugger.visible && FlxG.game.debugger.console.visible && e.keyCode == Keyboard.TAB) {
don't cuddle brackets
```suggestion
			if (FlxG.debugger.visible && FlxG.game.debugger.console.visible && e.keyCode == Keyboard.TAB)
			{
```

2023-05-23 21:01 UTC, Geokureli commented on flixel/system/debug/console/Console.hx
> +			e.preventDefault();
do we want to preventDefault on all keys, or just on tab? should we prevent it on all targets? does this issue happen on all targets?

I'm thinking "no" for all 3

2023-05-23 21:02 UTC, Geokureli commented on flixel/system/debug/console/Console.hx
> +			if (FlxG.debugger.visible && FlxG.game.debugger.console.visible && e.keyCode == Keyboard.TAB) {
also why add the bracket here in the first place, at first I assumed it was to include `e.preventDefault();`

2023-05-23 21:11 UTC, Geokureli approved these changes

2023-05-23 21:13 UTC, Geokureli commented
Thanks, I still need to test this on my windows pc. Also when i press tab on mac it just crashes (tried on dev, btw) Was gonna see why, and see if this fixes that

2023-05-23 21:46 UTC, Geokureli commented
linking this as it seems related:
https://github.com/openfl/openfl/issues/1856

2023-05-23 22:09 UTC, Geokureli requested changes

2023-05-23 22:09 UTC, Geokureli commented on flixel/system/debug/console/Console.hx
> +			#if windows
nitpicky, I know but please put an empty line above here. I always try to put one empty after an if's block
```suggestion

			#if windows
```

2023-05-23 22:20 UTC, Geokureli commented
Also I tried these steps on my windows pc (without your changes):
> Build any project with FLX_DEBUG enabled.
> While in-game, press TAB.

the "actual behavior" you describe doesn't happen for me, not sure if it's becuase it's windows 11, I can try my win10 pc. But the system mouse appears when i press "~" revealing the debug menu, not when i press tab. My game doesn't lose focus in any way, i'm still able to control it.

2023-05-23 22:38 UTC, Geokureli commented
I wasn't seeing the issue because I didn't have hscript installed. with hscript installed I now see that pressing tab is a way to select the console input, which seems to pause the game. Unfortunately this change doesn't prevent that, and even clicking the console field pauses the game

2023-05-24 00:23 UTC, EliteMasterEric commented
> Also I tried these steps on my windows pc (without your changes):
> > Build any project with FLX_DEBUG enabled.
> > While in-game, press TAB.
> 
> the "actual behavior" you describe doesn't happen for me, not sure if it's because it's windows 11, I can try my win10 pc. But the system mouse appears when i press "~" revealing the debug menu, not when i press tab. My game doesn't lose focus in any way, i'm still able to control it.

To clarify on the symptoms 

If the debug menu is open, pressing TAB switches focus to the text field for the console.

If the debug menu is CLOSED, pressing TAB seems to switch focus to the inactive element causing focus to detach from Flixel entirely.

2023-05-24 13:11 UTC, Geokureli commented
> If the debug menu is CLOSED, pressing TAB seems to switch focus to the inactive element causing focus to detach from Flixel entirely.
I tried this as well, and saw no issue on any of my machines. maybe it's because I didn't create any textFields?

2023-05-24 18:21 UTC, NeeEoo commented
I thought #2760 fixed this issue

2023-05-24 19:32 UTC, Geokureli commented
@EliteMasterEric can you try and confirm that the issue is still happening to you on the latest release? not sure if you made this branch based on experiences happening prior to upgrading to flixel 5.3

2023-05-24 19:53 UTC, EliteMasterEric commented
> @EliteMasterEric can you try and confirm that the issue is still happening to you on the latest release? not sure if you made this branch based on your experiences prior to upgrading to flixel 5.3. especially since I cannot reproduce the error

It looks like I was on an old branch and hadn't fast-forwarded. The issue appears to be resolved now.

2023-05-24 19:53 UTC, closed without merging