Update README.md
HaxeFlixel/flixel pull request #2830
Opened 2023-06-02 07:27 UTC by neondev27

Added path to Turkish translation

2023-06-02 20:42 UTC, neondev27 commented
That means i need to repull request with your suggestions?

2023-06-02 21:12 UTC, neondev27 commented
I did changes you said @Geokureli.

2023-06-02 21:33 UTC, Geokureli requested changes
1. some formatting issues
2. link to haxeflixel pages
3. I think CONTRIBUTING.md should have a link to turkish and CONTRIBUTING_TR.md should have a link to english as well

2023-06-02 21:33 UTC, Geokureli commented on CONTRIBUTING_TR.md
> +Hata bildirdiğiniz zaman, size sunulan [sorun şablonu](https://github.com/HaxeFlixel/flixel/blob/dev/.github/ISSUE_TEMPLATE.md)nu basit bir biçimde doldurun.
```suggestion
Hata bildirdiğiniz zaman, size sunulan [sorun şablonu](https://github.com/HaxeFlixel/flixel/blob/dev/.github/ISSUE_TEMPLATE.md) nu basit bir biçimde doldurun.
```
all throughout the new files, I see spaces after links have been removed, this makes it look odd, like in the image below
<img width="622" alt="Screenshot 2023-06-02 at 4 21 45 PM" src="https://github.com/HaxeFlixel/flixel/assets/2609513/c31ea373-99da-4374-8a50-7835c0a0c204">

2023-06-02 21:33 UTC, Geokureli commented on CONTRIBUTING_TR.md
> +HaxeFlixel'e katkıda bulunduğunuz için teşekkürler!
this file should should be in the .github folder with the original CONTRIBUTING.md

2023-06-02 21:33 UTC, Geokureli commented on README_TR.md
> +Eğer kod katkısında bulunmak veya hata bildirmek istiyorsanız, lütfen [CONTRIBUTING.md](https://github.com/neondev27/flixel/blob/dev/.github/CONTRIBUTING_TR.md)'mizi inceleyin.
add space and change link from neondev27 to haxeflixel's .github version
```suggestion
Eğer kod katkısında bulunmak veya hata bildirmek istiyorsanız, lütfen [CONTRIBUTING.md](https://github.com/HaxeFlixel/flixel/blob/dev/.github/CONTRIBUTING_TR.md) 'mizi inceleyin.
```

2023-06-02 21:33 UTC, Geokureli commented on README_TR.md
> +HaxeFlixel, [Adam “Atomic” Saltsman](http://www.adamatomic.com/) tarafından yapılan [Flixel'in ActionScript3 versiyonu](https://github.com/AdamAtomic/flixel)ndan köklerini almaktadır. 2011'de [Alexan
```suggestion
HaxeFlixel, [Adam “Atomic” Saltsman](http://www.adamatomic.com/) tarafından yapılan [Flixel'in ActionScript3 versiyonu](https://github.com/AdamAtomic/flixel) ndan köklerini almaktadır. 2011'de [Alexander Hohlov](https://github.com/beeblerox) tarafından AS3 kod tabanının ve Richard Davey'in [Flixel Güç Araçları](http://www.photonstorm.com/flixel-power-tools) nın Haxe portu olarak başladı.

```

2023-06-02 21:33 UTC, Geokureli commented on README_TR.md
> +HaxeFlixel'in bugünkü sürümü, [çekirdek ekibin](https://github.com/orgs/HaxeFlixel/people) ve [100'ün üzerinde katkıda bulunanları](https://github.com/HaxeFlixel/flixel/graphs/contributors) sayesinde
```suggestion
HaxeFlixel'in bugünkü sürümü, [çekirdek ekibin](https://github.com/orgs/HaxeFlixel/people) ve [100'ün üzerinde katkıda bulunanları](https://github.com/HaxeFlixel/flixel/graphs/contributors) sayesinde bugünkü halini aldı. Yalnızca çekirdek motorunda değil birçok önemli gelişme ve yeni özellik görmenin yanı sıra, daha zengin bir ekosistem de ek kütüphanelerle ve [80'den fazla demo projesi](https://github.com/HaxeFlixel/flixel-demos) yle öğrenmeye olanak sağlamaktadır.

```

2023-06-02 21:33 UTC, Geokureli commented on README_TR.md
> +[flixel](https://github.com/HaxeFlixel/flixel) | [eklentiler](https://github.com/HaxeFlixel/flixel-addons) | [ui](https://github.com/HaxeFlixel/flixel-ui) | [demolar](https://github.com/HaxeFlixel/fl
optional: link back to english?
```suggestion
[flixel](https://github.com/HaxeFlixel/flixel) | [eklentiler](https://github.com/HaxeFlixel/flixel-addons) | [ui](https://github.com/HaxeFlixel/flixel-ui) | [demolar](https://github.com/HaxeFlixel/flixel-demos) | [araçlar](https://github.com/HaxeFlixel/flixel-tools) | [şablonlar](https://github.com/HaxeFlixel/flixel-templates) | [dökümanlar](https://github.com/HaxeFlixel/flixel-docs) | [haxeflixel.com](https://github.com/HaxeFlixel/haxeflixel.com) | [english](https://github.com/HaxeFlixel/flixel/blob/dev/README.md)
```

2023-06-02 21:33 UTC, Geokureli commented on README.md
> +[flixel](https://github.com/HaxeFlixel/flixel) | [addons](https://github.com/HaxeFlixel/flixel-addons) | [ui](https://github.com/HaxeFlixel/flixel-ui) | [demos](https://github.com/HaxeFlixel/flixel-d
this still links to the external fork
```suggestion
[flixel](https://github.com/HaxeFlixel/flixel) | [addons](https://github.com/HaxeFlixel/flixel-addons) | [ui](https://github.com/HaxeFlixel/flixel-ui) | [demos](https://github.com/HaxeFlixel/flixel-demos) | [tools](https://github.com/HaxeFlixel/flixel-tools) | [templates](https://github.com/HaxeFlixel/flixel-templates) | [docs](https://github.com/HaxeFlixel/flixel-docs) | [haxeflixel.com](https://github.com/HaxeFlixel/haxeflixel.com) | [turkish](https://github.com/HaxeFlixel/flixel/blob/dev/README_TR.md)
```

2023-06-03 07:17 UTC, neondev27 commented
It is final look of the things. I wish it helped, @Geokureli

2023-06-03 07:17 UTC, neondev27 commented
If anything else needed, call.me from here or @ NeoDev27 in Twitter

2023-06-05 16:09 UTC, Geokureli approved these changes

2023-06-05 16:46 UTC, merged

2023-06-05 16:46 UTC, Geokureli commented
Thanks!