FlxGame: make the filters array public
HaxeFlixel/flixel pull request #2910
Opened 2023-08-31 17:27 UTC by Sword352

I remember doing something similar to FlxCamera, that would be nice to do the change to FlxGame as well

2023-08-31 17:52 UTC, Geokureli commented
> home/runner/work/flixel/flixel/flixel/FlxGame.hx:148: characters 13-20 : Redefinition of variable filters in subclass is not allowed. Previously declared at openfl.display.DisplayObject

2023-08-31 17:59 UTC, Geokureli requested changes
FlxGame extends DisplayObject with has `public var filters(get, set):Array<BitmapFilter>;`
https://github.com/openfl/openfl/blob/develop/src/openfl/display/DisplayObject.hx#L462
the only solution I see is that we should keep _filters, and make the getter set _filters and instead of 
```hx
filters = filtersEnabled ? _filters : null;
```
it should do 
```hx
super.set_filters(filtersEnabled ? _filters : null);
```

2023-08-31 17:59 UTC, Geokureli commented on flixel/FlxGame.hx
> +		filters = filtersEnabled ? filters : null;
This doesn't seem right

2023-08-31 17:59 UTC, Geokureli commented on flixel/FlxGame.hx
> +         */
indented with 8 spaces, should use 1 tab

2023-09-01 03:29 UTC, Sword352 commented
Did a few changes, this should be good now

2023-09-01 14:48 UTC, Geokureli commented
still failing on flash with haxe 4.2.5

2023-09-02 06:33 UTC, Sword352 commented
Alright so there is a weird error with flash saying that flash.display.Sprite does not have a filters field, but when adding a conditional block for only compiling the override keyword to non-flash targets, it stil says it needs to be overrided on flash.
How can we solve that issue?

2023-09-02 14:32 UTC, Sword352 commented
Closing this, will rework on that later after i fix the flash issue

2023-09-02 14:32 UTC, closed without merging