Use `FlxColorInt` instead of `Int` for RGBA to reduce variable size for CPP target
HaxeFlixel/flixel pull request #3167
Opened 2024-06-05 06:13 UTC by Just-Feeshy

It is just an area for memory usage optimization for the CPP target.

2024-06-05 17:19 UTC, Geokureli requested changes
Looks like [this test](https://github.com/HaxeFlixel/flixel/blob/dev/tests/unit/src/flixel/util/FlxColorTest.hx) is failing on cpp with the error:
> FAIL: massive.munit.AssertionException: Value [-32768] was not equal to expected value [-65536] at flixel.util.FlxColorTest#subtractNotSame (63)

I wish these test output hex strings instead of decimal, a quick conversion reveals the expected value is `FFFF0000` 
 but the actual value is `FFFF8000`

2024-06-05 17:24 UTC, Geokureli commented on flixel/util/FlxColor.hx
> +abstract FlxColor(Int) from Int from UInt to Int to UInt #if cpp from cpp.UInt8 to cpp.UInt8 #end
Shouldn't this be removed? a color's components may be constructed from or deconstructed to UInt8s but a color itself should always a 32 bit number

2024-06-05 17:27 UTC, Geokureli commented
furthermore, I'm a little skeptical of the benefits without seeing actual test results, please do some tests and ensure the following:
- is there any performance hit due to casting from UInt8 to Ints and vice versa?
- it there a measurable difference in memory usage from this

2024-06-05 18:59 UTC, Just-Feeshy commented
I'm so sorry, I forgot to take account for the rest of the methods when doing my own test.

2024-06-05 20:28 UTC, closed without merging

2024-06-05 21:23 UTC, Geokureli commented
@Just-Feeshy is this not salvageable?

2024-06-06 09:18 UTC, Just-Feeshy commented
> @Just-Feeshy is this not salvageable?

It is, but I realized I made some initial mistakes on the placement of `FlxColorInt` and I'm also trying to think of a good test to demonstrate with as little time as possible.