Implement FlxFlicker.pause() and FlxFlicker.resume()
HaxeFlixel/flixel pull request #3179
Opened 2024-06-12 17:48 UTC by EliteMasterEric

During the development of Funkin', I found the need to pause an active FlxFlicker without actively destroying it and recreating it. This PR adds that functionality.

2024-06-12 18:01 UTC, Geokureli commented
Down to merge, but note that `FlxTween.flicker` now exists which has all the same tween methods for pausing, resuming and cancelling. It also allows for custom "ease" logic, so you can use one tween to do a flicker that changes frequency rather than using two calls, like you mentioned

2024-06-12 18:09 UTC, EliteMasterEric commented
> Down to merge, but note that `FlxTween.flicker` now exists which has all the same tween methods for pausing, resuming and cancelling. It also allows for custom "ease" logic, so you can use one tween to do a flicker that changes frequency rather than using two calls, like you mentioned

Good to know, thanks for that.

2024-06-12 18:17 UTC, Geokureli commented on flixel/effects/FlxFlicker.hx
> +		if (timer == null) return;
```suggestion
		if (timer == null)
			return;
```

2024-06-12 18:17 UTC, Geokureli commented on flixel/effects/FlxFlicker.hx
> +		if (timer == null) return;
```suggestion
		if (timer == null)
			return;
		
```

2024-06-12 18:23 UTC, Geokureli requested changes
see suggestions

2024-06-12 20:30 UTC, Geokureli commented on flixel/effects/FlxFlicker.hx
> +	public function pause():Void {
```suggestion
	public function pause():Void
	{
```

2024-06-12 20:30 UTC, Geokureli commented on flixel/effects/FlxFlicker.hx
> +	public function resume():Void {
```suggestion
	public function resume():Void
	{
```

2024-06-13 02:22 UTC, Geokureli approved these changes

2024-06-13 02:22 UTC, merged

2024-06-13 02:31 UTC, Geokureli commented
Thanks!