Add "insert" function to the CameraFrontEnd like in FlxGroups
HaxeFlixel/flixel pull request #3290
Opened 2024-11-20 21:56 UTC by T5mpler

Simple pull request that adds an insert function to the CameraFrontEnd class incase you want a camera to render in-between another camera in the list (I'm surprised this didn't exist already unless there's a reason).

2024-11-20 22:01 UTC, T5mpler commented
Billezen back again 😔

2024-11-21 01:34 UTC, system32unknown commented
hi t5

2024-11-24 17:49 UTC, Geokureli requested changes
Mostly style changes. I also made insert match the behavior of haxe's Array.insert

2024-11-24 17:49 UTC, Geokureli commented on flixel/system/frontEnds/CameraFrontEnd.hx
> +	public function insert<T:FlxCamera>(NewCamera:T, Position:Int, DefaultDrawTarget:Bool = true):T
The official rule is to use lowercase arg names, we are slowly changing old uppercase args as we  go

2024-11-24 17:49 UTC, Geokureli commented on flixel/system/frontEnds/CameraFrontEnd.hx
> +	}
```suggestion
	/**
	 * Inserts a new camera object to the game.
	 * 
	 * - If `position` is negative, `list.length + position` is used
	 * - If `position` exceeds `list.length`, the camera is added to the end.
	 *
	 * @param	newCamera         The camera you want to add.
	 * @param	position          The position in the list where you want to insert the camera
	 * @param	defaultDrawTarget Whether to add the camera to the list of default draw targets. If false, 
	 *                            `FlxBasics` will not render to it unless you add it to their `cameras` list.
	 * @return	This FlxCamera instance.
	 */
	public function insert<T:FlxCamera>(newCamera:T, position:Int, defaultDrawTarget = true):T
	{
	    // negative numbers are relative to the length (match Array.insert's behavior)
	    if (position < 0)
	        position += list.length;
	    
	    // invalid ranges are added (match Array.insert's behavior)
        if (position >= list.length)
            return add(newCamera);
        
        final childIndex = FlxG.game.getChildIndex(list[position]);
        FlxG.game.addChildAt(newCamera.flashSprite, childIndex);
		
		list.insert(position, newCamera);
		if (defaultDrawTarget)
			defaults.push(newCamera);
		
		for (i in position...list.length)
			list[i].ID = i;
		
		cameraAdded.dispatch(newCamera);
		return newCamera;
	}
```

2024-11-24 17:49 UTC, Geokureli approved these changes

2024-11-24 17:56 UTC, Geokureli commented on flixel/system/frontEnds/CameraFrontEnd.hx
> +        final childIndex = FlxG.game.getChildIndex(list[position]);
```suggestion
        final childIndex = FlxG.game.getChildIndex(list[position].flashSprite);
```

2024-11-24 21:55 UTC, T5mpler commented
Ah got it! I only did the naming and stuff like that because  I was trying to match how the other functions did it in CameraFrontEnd, much appreciations!

2024-11-24 22:12 UTC, merged

2024-11-24 22:13 UTC, Geokureli commented
> Ah got it! I only did the naming and stuff like that because I was trying to match how the other functions did it in CameraFrontEnd, much appreciations!

Makes sense, thanks!