Update outdated documentation for BitmapFrontEnd.
HaxeFlixel/flixel pull request #3313
Opened 2024-12-11 18:07 UTC by glintfishGH

- Changed arguments to start with a lowercase letter.
- Fixed documentation ported over from flash(?), where the documented @:params would not align to function arguments.

2024-12-11 18:19 UTC, Geokureli commented
Oh I just merged this, thinking it was you
https://github.com/HaxeFlixel/flixel/pull/3312

2024-12-11 18:43 UTC, Geokureli requested changes

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * Caches a specified FlxGraphic object.
```suggestion
	 * Caches the specified graphic.
```

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @return	Cached FlxGraphic object.
```suggestion
	 * @return	The cached graphic.
```

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * Creates a new FlxGraphic object (a colored rectangle) and caches it.
```suggestion
	 * Creates a new graphic of a colored rectangle and caches it.
```

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @param	Key	The key identifying the bitmap.
Doc params should:
- start with lowercase letters
- have 3 spaces before the arg name and at least 2 after
- have all arg descriptions start on the same column
Other function doc rules:
- `@return` should have 2 spaces after, so the description aligns with the params
- Types should be wrapped in `backticks`
- Avoid types in args with default values (`unique:Bool = false` can be `unique = false`)

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @return	The FlxGraphic we just created.
here's an example of the formatting, and lets just call it a "graphic" not a "`FlxGraphic` object"
```suggestion
	 * @param   width   How wide the rectangle should be.
	 * @param   height   How high the rectangle should be.
	 * @param   color     What color the rectangle should be (0xAARRGGBB).
	 * @param   unique  Ensures that the bitmap data uses a new slot in the cache.
	 * @param   key       Force the cache to use a specific Key to index the bitmap.
	 * @return  The created graphic.
```

All of these suggestions can and should be committed using the dropdown below each. Please update the other methods

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	public function create(width:Int, height:Int, color:FlxColor, unique:Bool = false, ?key:String):FlxGraphic
```suggestion
	public function create(width:Int, height:Int, color:FlxColor, unique = false, ?key:String):FlxGraphic
```

2024-12-11 18:43 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
>  	 * @param	graphic	FlxGraphic to store in the cache.
```suggestion
	 * @param   graphic  The graphic to cache.
```

2024-12-11 20:21 UTC, glintfishGH commented
For future reference, where are the doc rules? didn't even know they existed

2024-12-11 20:29 UTC, Geokureli commented
lol they aren't formally listed anywhere. I should make that

2024-12-12 18:51 UTC, Geokureli requested changes

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @param	Key	The key identifying the bitmap.
- make `key` lower case
- put 2 spaces after `key` and 3 before (currently a tab)

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @return	The cached graphic.
```suggestion
	 * @return  The cached graphic.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @param	key	The FlxGraphics key (or name).
```suggestion
	 * @param	key	 The FlxGraphics key (or name).
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @return The BitmapData's key or null if there isn't such BitmapData in cache.
```suggestion
	 * @param   bmd  BitmapData to find in the cache.
	 * @return   The BitmapData's key or null if there isn't such BitmapData in cache.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @param	source BitmapData source class.
```suggestion
	 * @param   source  BitmapData source class.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
>  	 * @return	Full name for provided class.
```suggestion
	 * @return  Full name for provided class.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @return	unique key.
```suggestion
	 * @param   baseKey  key's prefix.
	 * @return  unique key.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @return	Generated key for spritesheet with inserted spaces between tiles.
```suggestion
	 * @param   baseKey       Beginning of the key. Usually it is the key for original spritesheet graphics (like "assets/tile.png").
	 * @param   frameSize     The size of tile in spritesheet.
	 * @param   frameSpacing  Offsets between tiles in offsets.
	 * @param   region        Region of image to use as spritesheet graphics source.
	 * @return  Generated key for spritesheet with inserted spaces between tiles.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @param graphic The object you want to remove and destroy.
```suggestion
	 * @param   graphic  The object you want to remove and destroy.
```

2024-12-12 18:51 UTC, Geokureli commented on flixel/system/frontEnds/BitmapFrontEnd.hx
> +	 * @param key Key of the cached FlxGraphic object.
```suggestion
	 * @param   key  Key of the cached graphic.
```

Calling it a "FlxGraphic object" is wordy and requires backticks, lets just say "graphic"

2024-12-12 19:02 UTC, glintfishGH commented
whoops, forgot that @ also tags people.

2024-12-12 19:33 UTC, moxie-coder commented
> whoops, forgot that @ also tags people.

lol, didn’t know someone had that GitHub name

2024-12-12 22:38 UTC, merged

2024-12-12 22:39 UTC, Geokureli commented
Thanks!